spring:
  application:
    name: ecommerc_shop
  datasource:
    username: root
    password: 2716
    url: jdbc:mysql://localhost:3306/prj_ecommerce
server:
  port: 8686
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true