spring:
  application:
    name: ecommerc_shop
  datasource:
    username: root
    password: 2716
    url: jdbc:mysql://localhost:3306/ecommerce
server:
  port: 8686
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
cloudinary:
  cloud-name: ${h1sdlryp}
  api-key: ${863611481138859}
  api-secret: ${0Gb20OqleiUVLtV3Hd_N1ue7SL8}